### ISSUE TITLE
Does not allow to change the snowflake role 

### ISSUE THREAD

**Issue by pramodrepaka** [Snowflake-Labs/Excelerator#14]
The role in snowflake is changed and it does not reflect in the excel. When I try to edit in config it does not give an option to edit the new role or it does not fetch the new role in snowflake.

**Comment by ssegal100** [comment]
What do you mean, the role in Snowflake has changed?
In config are you clicking on 'User Role' label? Are you seeing the 'Select Role and Warehouse' dialog? 
If so what are you seeing?

**Comment by ssegal100** [comment]
@pramodrepaka Is this resolved yet?
If not let me know what you are seeing.
Thanks,
Steve
