### ISSUE TITLE
Upload error to new table in schema with quoted, lowercase name containing "/"

### ISSUE THREAD

**Issue by daniel-sali** [Snowflake-Labs/Excelerator#15]
Hi,

I'm having issues uploading table data to a new table in a database and schema with a case-sensitive, lowercase quoted name. The names of the database and schema also contain the "/" character, I'm not sure if this is relevant.

The error happens after the "create or replace stage ... " statement is issued to Snowflake.

Upload of the same data succeeds to a database/schema with a case-insensitive, unquoted name.

I'm using version 1.1.10 of the add-in

Could you identify and eliminate the cause? We have a lot of case-sensitive, quoted database object names which we can't change.

Thanks,
Daniel

**Comment by ssegal100** [comment]
Hi Daniel. Are the column names in the header actually quoted?
If so would you try it without the quotes. It should be by default case sensitive. 
Also, I'm not sure about the "/". I'll have to look at that. 
Thanks.
Steve

**Comment by daniel-sali** [comment]
Hi,
No, the column names are not quoted, this is the data I'm trying to load:
<img width="355" alt="Screenshot 2021-02-10 at 17 15 28" src="https://user-images.githubusercontent.com/13250673/107538033-d4ec9000-6bc3-11eb-9491-8edcd671d164.png">
If there is a way I can capture VB error messages, let me know, I'd be happy to check and share logs.
Thanks,
Daniel

**Comment by ssegal100** [comment]
This should be good enough info for me to reproduce. I'll let you know if I need anymore info.
What timezone are you in?
Steve

**Comment by daniel-sali** [comment]
I'm in the CET time zone GMT+1.

**Comment by ssegal100** [comment]
Daniel,
I'm able to upload the worksheet like the one you have. 
So the table doesn't exist and you are trying to create it with the add-in, right?
There's not a simple way to capture the VB error if it's not already throwing one. Are you seeing a pop up with an error message?
Can we do a zoom call tomorrow morning so you can walk me through it?

**Comment by daniel-sali** [comment]
Thanks for taking a look, I'm available tomorrow for a zoom call from 9:30
CET.
You can contact me directly at daniel.sali >at< alphacruncher.com .
I'm getting an error popup, yes, I'd be happy to show you when and how.

Thanks,
Daniel

**Comment by ssegal100** [comment]
@daniel-sali Please download v 1.1.11 and let me know if that works for you. 
Thanks.
Steve

**Comment by daniel-sali** [comment]
Hi Steve,

Thank you for the call and the quick fix, I can confirm that I could upload my data to a new table in the database/schema with the quoted name containing "/".

Thanks,
Daniel
