### ISSUE TITLE
TimeStamp

### ISSUE THREAD

**Issue by GouriprasadMP** [Snowflake-Labs/Excelerator#18]
Hi,
When  I load data I am facing issue if the data type is Timestamp in the table ...
I teseted with mutilple tables I am unable to load data is data type is Timestamp
Any idea why this is happening
Warm Regards,

**Comment by ssegal100** [comment]
Would you send me an example of the file or a screenshot. I need to see what you are actually loading.
Also what is the error you are getting?
Look in the History tab of the Snowflake UI and see if anything failed and what that error message is.
Thanks.

**Comment by GouriprasadMP** [comment]
Sure,let me try

**Comment by ssegal100** [comment]
@GouriprasadMP I believe this issue has been resolved right?
Would you add the solution and then close the issue?
Thanks.

**Comment by TonyGaul** [comment]
@ssegal100 I had this issue last week and ended up choosing a text data type.  I am not sure if it is fixed.  Will leave the OP to update but can dig something up if need required.

**Comment by TonyGaul** [comment]
@ssegal100 In the xslx I have a datetime field called "FieldTimestamp", the first value is "2021-19-01 06:28:42".  The Excel custom format is "yyyy-mm-dd hh:mm:ss".  When uploading to Snowflake I get this error: "Timestamp '2021-19-01 06:28:42' is not recognized File '<DATABASE>.<SCHEMA>.<TABLE>TEMP.CSV.gz', line 3, character 39 Row 1, column "<TABLE>"["FieldTimestamp":6] If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client."

I have tried setting a number of different Snowflake Timestamp format config values such as:
yyyy-mm-dd hh:mm:ss
yyyy-MM-dd HH:mm:ss
YYYY-MM-DD HH:MM:SS
YYYY-MM-DD HH24:MI:SS

Have tried different Excel custom formats too.

**Comment by TonyGaul** [comment]
@ssegal100 Hi, after re-reading my comment, I realised that although the Excel custom format is showing "yyyy-mm-dd hh:mm:ss", the actual cell value is being displayed as "yyyy-dd-mm hh:mm:ss".  Therefore a Snowflake timestamp configuration of "YYYY-DD-MM HH24:MI:SS" worked.  So I do not have any problem with this issue and other xlsx files with datetime value work.  Thanks.

**Comment by ssegal100** [comment]
@TonyGaul Thanks for the follow up.
