### ISSUE TITLE
Add In gets Removed when Excel is closed and reopened

### ISSUE THREAD

**Issue by terry-campbell-od** [Snowflake-Labs/Excelerator#20]
The latest version of the AddIn (SnowflakeExcelAddin.xlam) does not persist between closing and reopening Excel (Version 2008  Build 13127.21216).  The menu items are removed and the addin must be readded via the Addin management window.

**Comment by terry-campbell-od** [comment]
[Excelerator Disappearing Issue.docx](https://github.com/Snowflake-Labs/Excelerator/files/6062950/Excelerator.Disappearing.Issue.docx)

**Comment by ssegal100** [comment]
Hi Terry. This commonly happens if you don't 'unblock' the file before installing. It's a windows security 'feature'. Here is a link to an article.:
https://exceloffthegrid.com/install-uninstall-excel-add/

Let me know if this helps.
Steve

**Comment by terry-campbell-od** [comment]
Thanks for the quick the reply.  Really appreciate it.


Terry Campbell
Sr. Manager, IT - Enterprise Intelligence Systems
6600 N. Military Trail | Boca Raton,  FL 33496
Tel: 561.438.6140 | Terry.Campbell@OfficeDepot.com<mailto:Terry.Campbell@OfficeDepot.com>

[Office Depot | Max]
CONFIDENTIALITY NOTICE: The information contained in this email and attached document(s) may contain confidential information that is intended only for the addressee(s). If you are not the intended recipient, you are hereby advised that any disclosure, copying, distribution or the taking of any action in reliance upon the information is prohibited. If you have received this email in error, please immediately notify the sender and delete it from your system.


________________________________

**Comment by trlinton** [comment]
Hi,  there is a section in the documenation that explains the issue and how
to resolve permission/security persisting the add-in

Thanks
