### ISSUE TITLE
Connect Cancel Button Cause Connect Error Going Forward

### ISSUE THREAD

**Issue by terry-campbell-od** [Snowflake-Labs/Excelerator#21]
When using the SnowflakeExcelAddin.xlam Add In, if I click Connect and then Cancel.  Every time afterwards I receive an error "**ERROR: Problem connecting: SQL compilation error:  Object does not exist, or operation cannot be performed.**"

This did go away once after my computer went to sleep over night but I was able to recreate by clicking Cancel from the Connect Window.

**Comment by ssegal100** [comment]
I'm not able to reproduce this one.
Does the error happen after you click OK once you entered the user/password? Are you using SSO or username and password?
Are you able to see what the last SQL executed was in Snowflake? If you look on the History tab in the Snowflake UI you should see a query executed with an error. Would you let me know what that is?
Thanks.

**Comment by terry-campbell-od** [comment]
I am using SSO.   Attached are screenshots.  The history was from an hour ago.  No new queries seem to be issued.

[cid:23401ae3-4ec4-473a-bf1d-2c2761e548db]


Thanks for the quick reply.  The tool is awesome when working!!!


Terry Campbell
Sr. Manager, IT - Enterprise Intelligence Systems
6600 N. Military Trail | Boca Raton,  FL 33496
Tel: 561.438.6140 | Terry.Campbell@OfficeDepot.com<mailto:Terry.Campbell@OfficeDepot.com>

[Office Depot | Max]
CONFIDENTIALITY NOTICE: The information contained in this email and attached document(s) may contain confidential information that is intended only for the addressee(s). If you are not the intended recipient, you are hereby advised that any disclosure, copying, distribution or the taking of any action in reliance upon the information is prohibited. If you have received this email in error, please immediately notify the sender and delete it from your system.


________________________________

**Comment by terry-campbell-od** [comment]
Good morning, I tried using the addin this morning after waking my laptop from hibernation.  I was able to connect the first time.  I closed excel.  I launched Excel again a little later and cannot connect to Snowflake.  I receive the **"ERROR: Problem connecting: SQL compilation error: Object does not exist, or operation cannot be performed.**".

![image](https://user-images.githubusercontent.com/31252005/111789642-c1ee6f00-8897-11eb-94e8-91cd4f54eaa0.png)

**Comment by terry-campbell-od** [comment]
Another user I am working with is having the same issue.

![image](https://user-images.githubusercontent.com/31252005/111791634-c61b8c00-8899-11eb-845a-3c33224eed1c.png)

**Comment by ssegal100** [comment]
Terry,
Would you check your version of the Add-in? Click the Config button in the Ribbon. You should see the version number at the top. If you don't have the latest (1.1.15), would you download it?
![image](https://user-images.githubusercontent.com/13276366/111804096-bef67d00-889d-11eb-851d-574648b7410a.png)

**Comment by terry-campbell-od** [comment]
I have 1.1.13.  I will update to 1.1.15.  Thanks.


Terry Campbell
Sr. Manager, IT - Enterprise Intelligence Systems
6600 N. Military Trail | Boca Raton,  FL 33496
Tel: 561.438.6140 | Terry.Campbell@OfficeDepot.com<mailto:Terry.Campbell@OfficeDepot.com>

[Office Depot | Max]
CONFIDENTIALITY NOTICE: The information contained in this email and attached document(s) may contain confidential information that is intended only for the addressee(s). If you are not the intended recipient, you are hereby advised that any disclosure, copying, distribution or the taking of any action in reliance upon the information is prohibited. If you have received this email in error, please immediately notify the sender and delete it from your system.


________________________________

**Comment by terry-campbell-od** [comment]
I installed 1.1.15 but extracting the new download over the existing files.  I updated the file properties and checked the unblock check box.  I was able to connect and run a query.

I closed Excel and reopened Excel.  I can no longer run queries.  I am receiving the same error.

[cid:01dab402-f40c-47ec-af12-6857a8de431b]

I am available for a debug session if you'd like.

Thanks.


Terry Campbell
Sr. Manager, IT - Enterprise Intelligence Systems
6600 N. Military Trail | Boca Raton,  FL 33496
Tel: 561.438.6140 | Terry.Campbell@OfficeDepot.com<mailto:Terry.Campbell@OfficeDepot.com>

[Office Depot | Max]
CONFIDENTIALITY NOTICE: The information contained in this email and attached document(s) may contain confidential information that is intended only for the addressee(s). If you are not the intended recipient, you are hereby advised that any disclosure, copying, distribution or the taking of any action in reliance upon the information is prohibited. If you have received this email in error, please immediately notify the sender and delete it from your system.


________________________________

**Comment by ssegal100** [comment]
Terry, as discussed this issue is due to the pseudo role ALL. 
The latest version of the Add-in 1.1.16, will set the role to an empty string if the previous Role used was ALL. This should prevent the error from occurring.
Please download the latest version and let me know if it works for you.
Thanks.
Steve

**Comment by terry-campbell-od** [comment]
Thanks Steven, I will download today and test it out.   Really appreciate the support.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by terry-campbell-od** [comment]
Steven,

1.1.16 is working great for me.  Thank you for the quick turnaround and the great tool!

Regards,
Terry


Terry Campbell
Sr. Manager, IT - Enterprise Intelligence Systems
6600 N. Military Trail | Boca Raton,  FL 33496
Tel: 561.438.6140 | Terry.Campbell@OfficeDepot.com<mailto:Terry.Campbell@OfficeDepot.com>

[Office Depot | Max]
CONFIDENTIALITY NOTICE: The information contained in this email and attached document(s) may contain confidential information that is intended only for the addressee(s). If you are not the intended recipient, you are hereby advised that any disclosure, copying, distribution or the taking of any action in reliance upon the information is prohibited. If you have received this email in error, please immediately notify the sender and delete it from your system.


________________________________

**Comment by ssegal100** [comment]
Great to hear Terry. It was great working with you on this.
Are both issue now resolved? If so would you close them out?
Thanks.
Steve

**Comment by terry-campbell-od** [comment]
Yes sir, both issues are resolved.  You can close issues #21 and #22.  Thanks again!


Terry Campbell
Sr. Manager, IT - Enterprise Intelligence Systems
6600 N. Military Trail | Boca Raton,  FL 33496
Tel: 561.438.6140 | Terry.Campbell@OfficeDepot.com<mailto:Terry.Campbell@OfficeDepot.com>

[Office Depot | Max]
CONFIDENTIALITY NOTICE: The information contained in this email and attached document(s) may contain confidential information that is intended only for the addressee(s). If you are not the intended recipient, you are hereby advised that any disclosure, copying, distribution or the taking of any action in reliance upon the information is prohibited. If you have received this email in error, please immediately notify the sender and delete it from your system.


________________________________
