### ISSUE TITLE
Cannot change the role

### ISSUE THREAD

**Issue by howardnguyen1211** [Snowflake-Labs/Excelerator#23]
the default role does not have any warehouse attached to it. want to change the default role, but it popped up the warehouse list which is empty.

**Comment by howardnguyen1211** [comment]
I fixed the problem.

**Comment by ssegal100** [comment]
@howardnguyen1211 What did you do to resolve the issue?

**Comment by howardnguyen1211** [comment]
change the default wh use cmd below, then replace the old add-ins file with the new one from git. since the old one had cached with the old role.

ALTER USER user SET DEFAULT_WAREHOUSE = 'new wh';

**Comment by ssegal100** [comment]
@howardnguyen1211 Thanks.
If this happens in the future, or if you need to change the role that is being used for login, you can right click on the tabs at the bottom of the worksheet and select Unhide:
![image](https://user-images.githubusercontent.com/13276366/112509307-58220980-8d5e-11eb-8e37-7932d19b0ad6.png)

Select the SnowflakeConfig worksheet. On this worksheet you can now change the Role that is used to login.
![image](https://user-images.githubusercontent.com/13276366/112509513-8e5f8900-8d5e-11eb-921b-51507c2b6318.png)

You probably want to hide that workbook when done.

**Comment by howardnguyen1211** [comment]
Nice! Thanks for letting me know that.
