### ISSUE TITLE
Support encryption key size 256

### ISSUE THREAD

**Issue by miro-licek** [Snowflake-Labs/Excelerator#27]
After we have updated [CLIENT_ENCRYPTION_KEY_SIZE](https://docs.snowflake.com/en/sql-reference/parameters.html#client-encryption-key-size) to 256 (from 128 default) users were not able to decrypt data from stage when using Excelerator. All other tools work well. According to documentation change could have affected only JDBC drivers, not ODBC.
the actual error message from SF logs is: "Failed to decrypt. Check file key and master key."
Excelerator can still connect and read data, but not write/update.
Could you please look at that? I tried searching through the VBA but could not find anything which would help.

Thank you

Miro

**Comment by ssegal100** [comment]
@miro-licek Did you open a support ticket and was it resolved?
Thanks.

**Comment by miro-licek** [comment]
Thx for following up. It was connected with encryption key size . When we extended it to 256 it affected loading into stage with ODBC which it shouldn't. We are following up with SF support. You can close this issue on your side. Thx
