### ISSUE TITLE
Errors when trying to change the database on upload or query in Snowflake Excelerator

### ISSUE THREAD

**Issue by troywinsett** [Snowflake-Labs/Excelerator#32]
When trying to upload data or even query data in Excel, it prompts me for the database change.  I make the change and it asks me to log in again.  I do that and get the error message below (must close or hide topmost modal form first).  

![image](https://user-images.githubusercontent.com/107204017/173151344-5008dfbd-cd93-483b-b231-35e2e6d62796.png)
<img width="897" alt="Snowflake Excel Error" src="https://user-images.githubusercontent.com/107204017/173151634-fb3d9dc0-9f48-431a-9c86-1538f7311513.PNG">

**Comment by ssegal100** [comment]
Hey Troy. I haven't seen this issue before but I'm happy to help out.
The first thing I notice that's off is the name of the schema, it's blank, but the table has 'Test' in it. Any idea on what's going on there? Did you enter 'Test' for the table?
Does the user you're logged in with have access the schemas in the DB that you selected?

**Comment by e16e** [comment]
@ssegal100 I'm the Snowflake SE working with Troy, and he shared his screen with me when he experienced this error (repeatedly).

There is a default db, schema, and table selected when he's prompted to authenticate. This appears to be the first db alphabetically in the account. 

Troy then selects the db, "DEMAND_SPREADSHEETS," he's prompted to authenticate again, which is successful. Troy's user account is the owner of the db. When he goes to select the schema, that's when the error appears.

**Comment by nicolasCreff** [comment]
I have the same since one day.
It was working well before.
(i work in sysadmin)

**Comment by ssegal100** [comment]
@nicolasCreff Did anything change in your environment? Was your operating system or Office/Excel version upgraded?

**Comment by nicolasCreff** [comment]
Yes i got an update of environment but i don't know what changed.
I will try to look later, i have not infinite time to understand the pb.
(i try to remove temp folder and to download again ).
I tried to put a query directly a got a strange result

**Comment by nicolasCreff** [comment]
Hi,
For me it's working again don't know why.
But in setting proxy it's work& ";proxy=<host>:<port>;"
But before it's was like if the complement was in read only or like if the security get activate again.
