### ISSUE TITLE
How to build + contribute?

### ISSUE THREAD

**Issue by javaguy44** [Snowflake-Labs/Excelerator#36]
Hi, I'd like to be able to build from source and possibly create a PR for improving

I cloned the repo but since there isn't a VS solution, I'm not sure how to compile?

Would appreciate build instructions so I can contribute

Thanks

**Comment by ssegal100** [comment]
@javaguy44 It would be great if could contribute. I've added a Build Guide to the repo. Please take a look at it.
VBA does not compile and the process for code control is tricky and not standard. I've created a 'src' directory where the code is exported to. 
Let me know if you have any questions. Would love to have you contribute. 
Thanks!
