### ISSUE TITLE
Question on "Update existing rows & Append new rows"

### ISSUE THREAD

**Issue by pankaj-k** [Snowflake-Labs/Excelerator#37]
Hi,

This is not an issue but I need some clarification and guidance. Let me know if you have a forum where I can ask this if this is not the place. 

Suppose I download 10 rows of data from table and then I add another row. I then upload it using the option "Update existing rows & Append new rows".
My understanding is that it will append the new row and also overwrite the existing 10 rows of data in the table in snowflake. 
Is there a way to just append the new row of data and keep the remaining rows of data in snowflake table as they are? 

Also if the table has a column set to autoincrement then is there a way to push data from Excelerator and let snowflake deal with incrementing the value in the column? I do not want to force my end users to increment and add id value while uploading the data.

Regards
PK

**Comment by ssegal100** [comment]
@pankaj-k Apologies for the late response. I didn't see this one.
There isn't a way to add the new rows and leave the others alone. Excelerator doesn't track the state/changes so it has to compare the data with what is in the table. 
For the autoincrement question, I believe if you leave the autoincrement out of the Excel spreadsheet it should work.  Please give that a try.
Again, apologies for missing this one.
Steve
