### ISSUE TITLE
snowflake excelerator error

### ISSUE THREAD

**Issue by BiToolkits** [Snowflake-Labs/Excelerator#4]
I installed snowflake excelerator add-in on Excel 365 (32bit). I have the 32bit Snowflake ODBC (v2.22) installed as well.
When try to connect to Snowflake, I receive the curl error code 3, "url using bad/illegal format or missing URL" oscode 9, "Bad file descriptor".
I am using Windows 10 Ent edition.
Any help is appreciated

**Comment by ssegal100** [comment]
Would you send me the server url that you used? Please blank out some characters for security.
I haven't seen this before, but let's start with the server url.

**Comment by BiToolkits** [comment]
Thank you for the quick reply. Below is the url:
https://pxxxe.xxx.aws.snowflakecomputing.com

**Comment by ssegal100** [comment]
You're welcome.
Would you try it without 'https://'?
Have you been able to test the ODBC connection separately?

**Comment by BiToolkits** [comment]
I apologize for the late respoinse.
The 'https://' is auto moved by Excelerator.
The SnowSQL works with 64bit ODBC driver. How do I test the 32bit ODBC driver? I don't find a SnowSQL 32bit.

**Comment by ssegal100** [comment]
I'm not sure the best way to test it. You can make sure its there by opening the 32 bit ODBC Manager and go to the Drivers tab and see if SnowflakeDSIIDriver is there, shown in the attachment.
If it's there, maybe we can do a Zoom call and I can take a look.
![ODBC Manager](https://user-images.githubusercontent.com/13276366/96038347-9d93ef80-0e2c-11eb-9f72-76497ee5eb7e.png)

**Comment by ssegal100** [comment]
@BiToolkits Hi. Has this been resolved? If so I'd like to close this issue.
Thanks.
Steve
