### ISSUE TITLE
Snowflake Add-In Querying Problems

### ISSUE THREAD

**Issue by MartinChisnall1964** [Snowflake-Labs/Excelerator#40]
Hello,

I am having issues with the Snowflake Excel Add-In and was wondering if anyone has any idea what the problem is?  

When querying Snowflake using the Excel Add-In I am having issues retrieving data. When I execute the SQL for a table/view it returns no data, no matter how long I wait. However if I then click the Connection icon twice, the data is then retrieved into Excel. If I then create a new sheet in the workbook and click Query, then the same table of data is retrieved automatically again. If I then change the SQL to execute against a different table/view, again no data is rertieved. If I click Connect the original set of data is retrieved and not the new table.

**Comment by ssegal100** [comment]
@MartinChisnall1964 Has this issue been fully resolved?

**Comment by MartinChisnall1964** [comment]
Yep all good now. Thanks for your help.
