### ISSUE TITLE
Upload Not Working

### ISSUE THREAD

**Issue by trelmthorf8** [Snowflake-Labs/Excelerator#41]
Hello, 

I downloaded the Excelerator for writebacks on May 16 (for Windows)
The Worksheet Version Number is 7.
The version # in the Configuration popup window is 1.1.19
Excel Version 2208

After modifying a cell and specifying a primary key column, then clicking UPLOAD, the following happens:

![image](https://github.com/Snowflake-Labs/Excelerator/assets/39713195/3f6462fd-afca-4733-b08a-79489643b8a1)

![image](https://github.com/Snowflake-Labs/Excelerator/assets/39713195/83f4b974-4826-4efc-ac0a-5f49c6563114)

In Snowflake's Activity page I can see the stage is created successfully and the PUT is successful.
I am not able to access the Excelerator Log tab - clicking UNHIDE doesn't reveal it, and when I create the tab myself and run the select & upload my LOG tab doesn't get populated.

Thanks for your help!

**Comment by ssegal100** [comment]
Hi @trelmthorf8. Are you able to do a 'Put' command using the CLI from the same machine that is running Excel? I'm wondering if there is a network issue.

**Comment by ssegal100** [comment]
Great, thanks for the follow up.
