### ISSUE TITLE
Issue Logging in

### ISSUE THREAD

**Issue by Rposada** [Snowflake-Labs/Excelerator#42]
when logging into snowflake; Excelerator first runs these commands bellow.

 

show databases;
WITH databases (a,name,b,c,d,e,f,g,h) as (select * from table(result_scan(last_query_id()))) select name from databases;

 

it seems there are 10 columns now when declaring "show databases". I am unable to use excelerator and I am getting the error "Mismatch between number of columns produced by 'DATABASES' and the number of aliases specified."

**Comment by Rposada** [comment]
Easy by updating the getDatabasecombobos Sub:
![image](https://github.com/Snowflake-Labs/Excelerator/assets/89848039/10a1764b-419b-4762-9085-1036a4e7e730)

**Comment by ssegal100** [comment]
Yes, that's the update. This issue occurs when a certain parameter is enabled in the Snowflake account that adds some columns to the view.
Another approach is to not use the "Select *" and explicitly get the columns needed. It's more resilient to change that way.
I'll see if I made this change in the latest release.
Steve

**Comment by SuccinctGasca** [comment]
Thanks! This really helps.
