### ISSUE TITLE
"SSL peer certificate or SSH remote key was not OK" error occurred

### ISSUE THREAD

**Issue by DaisukeOtaka** [Snowflake-Labs/Excelerator#5]
Hi,

I've tried to use the Excelerator Add-in today, but when I connect to snowflake server, following error occurred. Does anybody have an idea how to resolve following error?
![image](https://user-images.githubusercontent.com/6836771/100619930-23c6af80-3361-11eb-92cc-906f70aab2e3.png)

OS: Windows10 Pro
Excel: Office 2016 (64bit)
ODBC Driver: snowflake64_odbc-2.22.2.msi

Best Regards,

**Comment by sfc-gh-gmullen** [comment]
This is usually because your network appliance is trying to inspect the encrypted traffic. Work with your network team and make sure you you added the SELECT$WHITELIST() endpoints to your list of allowed exceptions on your network appliance or firewall.

**Comment by DaisukeOtaka** [comment]
Thank you for your reply.

I'm working from home now, and I don't configure any special settings on my router. There is no issue with snowcd and snowsql, so it looks like no network access issue for the endpoints.

```
c:\tmp>snowcd allowlist.json
Performing 30 checks for 12 hosts
All checks passed
```
SnowCD (Connectivity Diagnostic Tool) — Snowflake Documentation
https://docs.snowflake.com/en/user-guide/snowcd.html

*I also tried it with the firewall off but the result was the same.

**Comment by ssegal100** [comment]
I'm looking into other possibilities, but would you double check that your Excel is actually 64bit. I haven't seen a 64 bit version even though the OS is.
Also, are you connecting through a VPN?

**Comment by DaisukeOtaka** [comment]
My Excel is looks like 64bit, but I will also try with 32bit snowflake odbc driver.
![image](https://user-images.githubusercontent.com/6836771/100818673-f592be00-348d-11eb-942d-815c5d3d234a.png)
![image](https://user-images.githubusercontent.com/6836771/100818953-86699980-348e-11eb-9769-2710d6d78643.png)

In addition, I'm connected to the internet directly without VPN. I will try with another network connection too.(smartphone tethering)

**Comment by DaisukeOtaka** [comment]
>My Excel is looks like 64bit, but I will also try with 32bit snowflake odbc driver.

I uninstalled the 64bit odbc driver and tried to install the 32bit odbc driver. Then I got an error saying that the driver could not be found, so my Excel seems to be correct with 64bit.
![image](https://user-images.githubusercontent.com/6836771/100820244-288a8100-3491-11eb-84e4-876f7d560f28.png)

>I will try with another network connection too.(smartphone tethering)

I also tried this, but the result did not change.

**Comment by Upendran29** [comment]
Hello All,

I'm facing the same problem with the code error 400.  I'm using windows 64 bit machine 


![image](https://user-images.githubusercontent.com/60202286/101225260-9d5ae800-3656-11eb-8a0e-e4fa3ded85f3.png)

**Comment by sara0529** [comment]
Hi All,

I'm facing the same issue.  I'm currently using 64 bit windows 10 pro and I have no restriction at snowflake firewall layer for my IP.  But still I'm getting code error 400 and I cannot successfully connect.

Note - I select SSO authentication and submit the connect request, automatic browser page is opening (as expected) and validating my connection with myOkta.  However, connection is Unsuccessful 

Appreciate your help or comments in fixing this.

![image](https://user-images.githubusercontent.com/75507953/101225569-66390680-3657-11eb-85a4-1c46e5b62ad6.png)

**Comment by ssegal100** [comment]
Sorry for the delay on these issues.
@DaisukeOtaka It does look like you have the correct driver. 
@sara0529 Would you please check if Excel is 64bit?

Do you guys know how to find the ODBC log files? Would you post them here?
Thanks.

**Comment by sara0529** [comment]
Hi Segal,

I'm yet to check the MS version for the machine which is facing issue.  However, I've tried connecting using 64-bit it is working.  Please let me know what is the software prerequisite to use excelerator from windows 10 64 bit machine.

![image](https://user-images.githubusercontent.com/75507953/101288863-7a4b4800-37be-11eb-8bb1-d27e332ff7d8.png)

**Comment by ssegal100** [comment]
@sara0529 
Sorry, but it's not clear. Are you saying you have not checked it yet? Is that version from a different machine?
How did you test the connection that is working?
The only prereqs should be the 64bit ODBC driver, which sounds like what you have.

Let me know if you can get the ODBC log files. Thanks.

**Comment by DaisukeOtaka** [comment]
@ssegal100
>Do you guys know how to find the ODBC log files? Would you post them here?
I've acknowledged. I will try to get the ODBC log later.

**Comment by DaisukeOtaka** [comment]
@ssegal100 
These are my ODBC log files.
*Due to GitHub's attachment file extension restrictions, I renamed "snowflake_odbc_curl.dmp" to "snowflake_odbc_curl.dmp.log".

[snowflake_odbc_connection_0.log](https://github.com/Snowflake-Labs/Excelerator/files/5652953/snowflake_odbc_connection_0.log)
[snowflake_odbc_driver.log](https://github.com/Snowflake-Labs/Excelerator/files/5652954/snowflake_odbc_driver.log)
[snowflake_odbc_generic0.log](https://github.com/Snowflake-Labs/Excelerator/files/5652955/snowflake_odbc_generic0.log)
[snowflake_odbc_curl.dmp.log](https://github.com/Snowflake-Labs/Excelerator/files/5652960/snowflake_odbc_curl.dmp.log)

ref.)
FAQ: Where is the Snowflake ODBC log file containing Tableau-generated SQL?
https://community.snowflake.com/s/article/faq-where-is-the-snowflake-odbc-log-file-containing-tableau-generated-sql


Should I download the pem file from somewhere and update it?
```
2020-12-07T13:35:39Z.580		[thread-5848]	Info	Hostname kya38912.us-east-1.snowflakecomputing.com was found in DNS cache.
2020-12-07T13:35:39Z.584		[thread-5848]	Info	  Trying 3.232.20.32:443....
2020-12-07T13:35:39Z.587		[thread-5848]	Info	TCP_NODELAY set.
2020-12-07T13:35:39Z.770		[thread-5848]	Info	Connected to kya38912.us-east-1.snowflakecomputing.com (3.232.20.32) port 443 (#0).
2020-12-07T13:35:39Z.774		[thread-5848]	Info	ALPN, offering http/1.1.
2020-12-07T13:35:39Z.790		[thread-5848]	Info	successfully set certificate verify locations:.
2020-12-07T13:35:39Z.792		[thread-5848]	Info	  CAfile: C:\Program Files\Snowflake ODBC Driver\etc\cacert.pem.  CApath: none.
2020-12-07T13:35:39Z.793		[thread-5848]	Info	TLSv1.3 (OUT), TLS handshake, Client hello (1):.
2020-12-07T13:35:40Z.133		[thread-5848]	Info	TLSv1.3 (IN), TLS handshake, Server hello (2):.
2020-12-07T13:35:40Z.135		[thread-5848]	Info	TLSv1.2 (IN), TLS handshake, Certificate (11):.
2020-12-07T13:35:40Z.137		[thread-5848]	Info	TLSv1.2 (OUT), TLS alert, unknown CA (560):.
2020-12-07T13:35:40Z.139		[thread-5848]	Info	SSL certificate problem: unable to get local issuer certificate.
2020-12-07T13:35:40Z.141		[thread-5848]	Info	Closing connection 0.
```

**Comment by ssegal100** [comment]
@DaisukeOtaka 
Thank you. I'm looking at it now. 
Do you know who the Solution Engineer is that supports your account?

**Comment by DaisukeOtaka** [comment]
@ssegal100 
I'm sorry, I found the reason of this issue. This was my PC environment issue.

**Step1. update cacert.pem**
I downloaded the file from the following site and updated it, but there was no change.

curl - Extract CA Certs from Mozilla
https://curl.haxx.se/docs/caextract.html

**Step 2. Change my antivirus soft (ESET) settings.**
I turned off the ESET setting called "Enable SSL/TLS protocol filtering" and **it works fine.**
```
2020-12-07T14:21:26Z.917		[thread-5309]	Info	TLSv1.3 (OUT), TLS handshake, Client hello (1):.
2020-12-07T14:21:27Z.095		[thread-5309]	Info	TLSv1.3 (IN), TLS handshake, Server hello (2):.
2020-12-07T14:21:27Z.097		[thread-5309]	Info	TLSv1.2 (IN), TLS handshake, Certificate (11):.
2020-12-07T14:21:27Z.134		[thread-5309]	Info	TLSv1.2 (IN), TLS handshake, Server key exchange (12):.
2020-12-07T14:21:27Z.141		[thread-5309]	Info	TLSv1.2 (IN), TLS handshake, Server finished (14):.
2020-12-07T14:21:27Z.152		[thread-5309]	Info	TLSv1.2 (OUT), TLS handshake, Client key exchange (16):.
2020-12-07T14:21:27Z.155		[thread-5309]	Info	TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):.
2020-12-07T14:21:27Z.157		[thread-5309]	Info	TLSv1.2 (OUT), TLS handshake, Finished (20):.
2020-12-07T14:21:27Z.334		[thread-5309]	Info	TLSv1.2 (IN), TLS handshake, Finished (20):.
```
[KB3126] Disable SSL filtering in ESET Windows products
https://support.eset.com/en/kb3126-disable-ssl-filtering-in-eset-windows-products


Thank you so much for your kind support!

**Comment by ssegal100** [comment]
Oh great to hear. Thanks for letting me know!
Connectivity issues are always tough to track down.
Now that you are connected, let me know if you have any questions with the Excelerator.

**Comment by ssegal100** [comment]
@sara0529
Would you open another issue so we can close out this one?
Do you know who your Solution Engineer is that is supporting your account?
Thanks.

**Comment by DaisukeOtaka** [comment]
The original issue has been resolved, so I'm going to close this ticket.

@sara0529 
If the problem persists, please open another issue.
