### ISSUE TITLE
Inserting data does overrides columns with defaults or autoincrement set.

### ISSUE THREAD

**Issue by PAPutzback** [Snowflake-Labs/Excelerator#8]
If I insert a row and leave the Primary key field empty since it is supposed to autogenerate the id on insert and\or I leave another column with the default set to CURRENT_TIMESTAMP(). Neither the ID or the date gets set. They end up being set to empty strings. Without the key this also makes deletes a bit of an issue and the user will need rules to add additional key fields.
Great Addin though. I'll just have to add some instructions for the users to look up the last ID and increment it by 1 and type in the date and time for the CREATE DATE field.

**Comment by ssegal100** [comment]
Hi @PAPutzback. If you are trying to only insert rows, then you can just leave those columns out. If you do that it will not explicitly set those columns to anything, so the defaults should work. You won't be able to do an insert and update in the same 'upload' function though.
Let me know if this could work for you. If you can think of a behavior change that can help, let me know.
Thanks.

**Comment by ssegal100** [comment]
@PAPutzback Is there any improvements that we can do to help? Maybe I'm not completely understanding the issue.
Thanks.

**Comment by ssegal100** [comment]
@PAPutzback Was there anything I can help with on this issue? If not I'd like to close it out.
Thanks.
Steve

**Comment by PAPutzback** [comment]
Sorry for not getting back to you. I got pulled off to another project.
Please close the ticket,

**Comment by ssegal100** [comment]
Thanks!
