### ISSUE TITLE
When I try to change my role or warehouse I get the error "Problem Initializing"

### ISSUE THREAD

**Issue by PAPutzback** [Snowflake-Labs/Excelerator#9]
I get the error when I click either link in User Data. When I close the error an Upload Status box appears with the text "Getting Roles..." and it never goes away. I can close it and it give me a dialog box with two dropdowns to select a Role and Warehouse. 

If I click OK on the config the debugger shows up along with a compile error "Method or data member not found". The break is on OKButton_Click.

**Comment by ssegal100** [comment]
@PAPutzback I'm looking at it now. I take it that you had already connected before trying to change the role/warehouse, right? 
Do you have time to do a web conf so I can step through it with you?
Thanks
Steve

**Comment by ssegal100** [comment]
@PAPutzback At the bottom of the Excel workbook there are tabs, maybe just one. Would you right click on it and select 'unhide'. In the menu that appears, click 'SnowflakeConfig'. 
What are the values for Warehouse and Role on the sheet that appears?

**Comment by ssegal100** [comment]
@PAPutzback I uploaded a new version with some better error handling. Please try that, it should provide more insight.
Also, when you get the error, look in the SQL History for you Snowflake account and let me know what the last SQL was.
Thanks.
Steve

**Comment by PAPutzback** [comment]
I'll check out the new version. I think you can delete this thread. I think the issue was because I was preparing a demo and when I reconnected the addin to Excel something broke. I restarted Excel and the problem went away. I appreciate the quick response.

One enhancement I could see would be a notification that there are backup tables from a previous session that need to be cleaned up. I notice after a couple crashes I had a few backups in my schema.

Which Upload step creates a backup as opposed to using Time Travel to restore changes?

**Comment by ssegal100** [comment]
OK, thanks. Let me know if you have any other issues.
I create a backup immediately when uploading, except if its a new table of course. I found this approach easier than using time travel, though you are right, these backup tables aren't always deleted. 
I like the idea of the notification and maybe asking the user if they want to clean up any back up tables.
Thanks.
